---
title             : "Estimating age-related change in infants’ linguistic and cognitive development using (meta-)meta-analysis"
shorttitle        : "Estimating change with meta-analysis"

author: 
  - name          : "Anjie Cao"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "450 Jane Stanford Way, Stanford, CA 94305"
    email         : "anjiecao@stanford.edu"
  - name          : "Molly Lewis"
    affiliation   : "2"
  - name          : "Sho Tsuji"
    affiliation   : "3"
  - name          : "Christina Bergmann"
    affiliation   : "3"
  - name          : "Alejandrina Cristia"
    affiliation   : "4"
  - name          : "Michael C. Frank"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "Stanford University "
  - id            : "2"
    institution   : "?"
  - id            : "3"
    institution   : "?"
  - id            : "4"
    institution   : "?"

authornote: |

  Enter author note here.

abstract: |
 Developmental psychology focuses on how psychological phenomena emerge with age. In cognitive development research, however, the specifics of this emergence is often underspecified. Researchers often provisionally assume linear growth by including chronological age as a predictor in regression models. In this work, we aim to evaluate this assumption by examining the functional form of age trajectories across 24 phenomena in early linguistic and cognitive development using (meta-)meta-analysis. Surprisingly, for most meta-analyses, the effect size for the phenomenon was relatively constant throughout development. We investigated four possible hypotheses explaining this pattern: (1) age-related selection bias against younger infants; (2) methodological adaptation for older infants; (3) change in only a subset of conditions; and (4) positive growth only after infancy. None of these explained the lack of age-related growth in most datasets. Our work challenges the assumption of linear growth in early cognitive development and suggests the importance of uniform measurement across children of different ages.

  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : 
    papaja::apa6_pdf:
      latex_engine: xelatex
      
header-includes   :
    - \usepackage{tabu}
    - \usepackage{tikz}
    - \usepackage{adjustbox}
    - \usepackage{float}
    - \usepackage{graphicx}
    - \usepackage{pdflscape}
    - \usepackage{lscape}
    - \usepackage{longtable}
    - \usepackage{tabu}
    - \usepackage{setspace}% http://ctan.org/pkg/setspace
    - \AtBeginEnvironment{longtable}{\singlespacing}{\small}
    



---




```{r setup, include = FALSE}
library("papaja")
library(here)
library(tidyverse)
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
d <- read_csv(here("data/metalab_data_mini.csv")) 

```

```{r child = "01_introduction.Rmd"}
```


# Estimating the functional forms of the developmental change in meta-analytic data

```{r child = "02_estimate_change.Rmd"}

```

```{r child = "03_interim_discussion.Rmd"}

```


# Understanding the lack of developmental change in meta-analytic data

```{r child = "04_h1.Rmd"}

```


```{r child = "05_h2.Rmd"}

```

```{r child = "06_h3.Rmd"}

```

```{r child = "07_h4.Rmd"}

```

```{r child = "08_general_discussion.Rmd"}

```


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
