---
title: "02_devo_curve_comparison.Rmd"
author: "anjie"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(metafor)
library(ggrepel)

d <- read_csv(here("data/metalab_data_mini.csv"))
source(here("helper/model_comparison_help.r"))
```
# Fit Models 

```{r}
age_models_df <- lapply(unique(d$ds_clean), 
       function(name){
         print(name)
         get_compare_IC_df(d, name, NULL)
       }) %>% 
  bind_rows()

saveRDS(age_models_df, here("cached_data/age_models_df.Rds"))
```

# visualization 

```{r}
age_models_df %>% 
  filter(ic == "AICc") %>% 
  select(REML, model_spec_clean, dataset) %>% 
  group_by(dataset) %>% 
  mutate(
    min_REML = (REML == min(REML))
  ) %>% 
  ggplot(aes(x = model_spec_clean, y = REML, color = min_REML)) + 
  geom_point() + 
  facet_wrap(~dataset, scales = "free") + 
  theme(legend.position = "none") + 
  theme_few()
```

```{r}
age_models_df %>% 
  filter(ic == "AICc") %>% 
  rename(Dataset = dataset) %>% 
  select(REML, model_spec_clean, Dataset) %>% 
  pivot_wider(names_from = model_spec_clean, 
              values_from = REML) %>% 
  kableExtra::kable(digits = 2)
```


```{r}

age_df_wide <- age_models_df %>% 
  filter(ic == "AICc") %>% 
  rename(Dataset = dataset) %>% 
  select(REML, model_spec_clean, Dataset) %>% 
  pivot_wider(names_from = model_spec_clean, 
              values_from = REML)

age_df_wide$min <- apply(age_df_wide[c('Linear','Log', 'Quadratic', 'Const')], 1, min)

# get the delta value 
age_df_wide <- age_df_wide %>% 
  mutate(d_linear = Linear - min, 
         d_log = Log - min, 
         d_quad = Quadratic - min, 
         d_const= Const - min) %>% 
  select(Dataset, d_linear, d_log, d_quad, d_const) %>% 
  rename(Linear = d_linear, 
         Log = d_log, 
         Quadratic = d_quad, 
         Const = d_const) %>% 
   mutate(across(where(is.numeric), round, 2)) 


age_df_wide %>% 
  pivot_longer(cols = c("Linear", "Log", "Quadratic", "Const")) %>% 
  ggplot(aes(x = reorder(Dataset, value), y = value, color = name)) +
  theme_few() + 
  geom_hline(yintercept = 4, linetype = 2, color = "gray") + 
  geom_hline(yintercept = 0, linetype = 3) + 
  geom_point(position = position_dodge(width = .2), 
             #color = "white"
             ) + 

  coord_flip()+ 
  xlab("") + 
  labs(color = "Functional form") + 
  guides(colour = guide_legend(nrow = 2))  + 
  theme(legend.position = "top")
```





