---
title: "07_bayeisanMA"
author: "Anjie Cao, Molly Lewis, and Michael Frank"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)

library(brms)
library(here)

# just try one dataset for now

d <- read_csv(here("data/cogsci_data/clean_data.csv")) %>% 
  filter(ds_clean == "Label advantage in concept learning")

```

heavily drawn from Chris's work 

```
model <- rma.mv(as.formula(formula), 
                    V = d_var_calc, 
                    random = ~ 1 | short_cite/same_infant/unique_row, 
                    data = current_df)
```

^^ this is the original basic model 

# intercept model 

```{r}

ma_estimate <- bf(d_calc | se(d_var_calc) ~ 1 + (1 | short_cite/same_infant/unique_row))

priors <- c(prior(normal(0, 2.5), class = Intercept),
            prior(normal(1, 1), class = sd),
            prior(gamma(2, 0.1), class = nu))


intercept_model <- 
  brm_multiple(
    ma_estimate,
    #save_pars = save_pars(all = TRUE),
    data = list(d), 
    family = student,
    prior = priors,
    file = here("cache_model","intercept_model"),
    sample_prior = T,
    iter = 9000, 
    warmup = 500,
    chains = 2,
    #backend = "cmdstanr",
    #threads = threading(2),
    control = list(
      adapt_delta = 0.999,
      max_treedepth = 20 ))

```

```{r}
pp_check(intercept_model, ndraws = 100)
#plot(intercept_model)

summary(intercept_model)
```

# age model 

```{r}
age <- bf(d_calc | se(d_var_calc) ~ mean_age_months + (1 | short_cite/same_infant/unique_row))


priors <- c(prior(normal(0, 2.5), class = Intercept),
            prior(normal(1, 1), class = sd),
            prior(gamma(2, 0.1), class = nu))


age_model <- 
  brm_multiple(
    age,
    #save_pars = save_pars(all = TRUE),
    data = list(d), 
    family = student,
    prior = priors,
    file = here("cache_model","age_model"),
    sample_prior = T,
    iter = 9000, 
    warmup = 500,
    chains = 2,
    #backend = "cmdstanr",
    #threads = threading(2),
    control = list(
      adapt_delta = 0.999,
      max_treedepth = 20 ))

```

```{r}
age_sq <- bf(d_calc | se(d_var_calc) ~ I(mean_age_months^2) + (1 | short_cite/same_infant/unique_row))


priors <- c(prior(normal(0, 2.5), class = Intercept),
            prior(normal(1, 1), class = sd),
            prior(gamma(2, 0.1), class = nu))


age_sq_model <- 
  brm_multiple(
    age,
    #save_pars = save_pars(all = TRUE),
    data = list(d), 
    family = student,
    prior = priors,
    file = here("cache_model","age_sq_model"),
    sample_prior = T,
    iter = 9000, 
    warmup = 500,
    chains = 2,
    #backend = "cmdstanr",
    #threads = threading(2),
    control = list(
      adapt_delta = 0.999,
      max_treedepth = 20 ))

age_log <- bf(d_calc | se(d_var_calc) ~ log(mean_age_months) + (1 | short_cite/same_infant/unique_row))



age_log_model <- 
  brm_multiple(
    age,
    #save_pars = save_pars(all = TRUE),
    data = list(d), 
    family = student,
    prior = priors,
    file = here("cache_model","age_log_model"),
    sample_prior = T,
    iter = 9000, 
    warmup = 500,
    chains = 2,
    #backend = "cmdstanr",
    #threads = threading(2),
    control = list(
      adapt_delta = 0.999,
      max_treedepth = 20 ))

```

```{r}
library(metafor)
f_age_model <- rma.mv(d_calc ~ mean_age_months, 
                    V = d_var_calc, 
                    random = ~ 1 | short_cite/same_infant/unique_row, 
                    data = d)

summary(f_age_model)
```

```{r}
loo(age_model)
loo(intercept_model)
age_model <- add_criterion(age_model, "loo", moment_match = TRUE)
intercept_model <- add_criterion(intercept_model, "loo", moment_match = TRUE)
age_log_model <- add_criterion(age_log_model, "loo")
age_sq_model <- add_criterion(age_sq_model, "loo")

loo_compare(intercept_model,age_model, age_log_model, age_sq_model)
```


