---
title: "table_materials"
author: "anjie"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(here)
library(metafor)
library(kableExtra)
library(xtable)
library(ggthemes)

source(here("helper/summary_table_help.r"))

d <- read.csv(here("data/metalab_data_mini.csv"))
summary_d <- readRDS(here("cached_data/summary_d.Rds"))
```

# summary table 

- name of phenomenon
- n studies
- n effects
- n kids
- age range
- mean age
- average effect size


```{r eval=FALSE, include=FALSE}
summary_d <- d %>% 
  group_by(ds_clean) %>% 
  nest(data = -ds_clean) %>% 
  mutate(mod = map(data, get_ma_effect_size), 
         descriptive = map(data, get_descriptive_stas)) %>% 
  unnest(c(mod, descriptive)) %>% 
  select(-data)

saveRDS(summary_d,here("cached_data/summary_d.Rds"))
```

```{r}
summary_d_print <- summary_d %>% 
  mutate(es_print = 
           paste0(round(es, 2), " [", round(es_lb, 2), ",", round(es_ub, 2), "]"), 
         mean_age_print = round(mean_age, 2), 
         n_kids_print = round(n_kids, 0),
         age_range_print = paste0("[", round(min_age, 2), ",", round(max_age, 2), "]")
           ) %>% 
  select(ds_clean, n_studies, n_effects, n_kids_print, mean_age_print, age_range_print, es_print ) %>% 
  arrange(ds_clean)
```




```{r}
summary_d_print %>% 
  kable( "latex", align = "l", digits = 2, 
      row.names = FALSE,
      col.names = c("Reseach Area",
                    "N Studies",
                    "N effect sizes",
                    "N participants", 
                    "Mean age (months)",
                    "Age range",
                    "Average Effect Size"
                    )) %>%
kable_styling(full_width = TRUE,
              bootstrap_options = c("condensed"))
```



```{r}
colnames(summary_d_print) <-c("Reseach Area",
                    "N Studies",
                    "N effect sizes",
                    "N participants", 
                    "Mean age (months)",
                    "Age range",
                    "Average Effect Size")


table <- xtable::xtable(as.matrix(summary_d_print),  
                        caption = "LMAO")
 
print.xtable(table, include.rownames = FALSE, comment = FALSE,
              size="\\fontsize{8pt}{9pt}\\selectfont")
 
```


# curve table 

```{r}
age_df <- readRDS(here("cached_data/age_models_df.Rds"))

age_df_wide <- age_df %>% 
  filter(ic == "AICc") %>% 
  rename(Dataset = dataset) %>% 
  select(REML, model_spec_clean, Dataset) %>% 
  pivot_wider(names_from = model_spec_clean, 
              values_from = REML)

age_df_wide$min <- apply(age_df_wide[c('Linear','Log', 'Quadratic', 'Const')], 1, min)


age_df_wide %>% 
  mutate(across(where(is.numeric), round, 2)) %>% 
  mutate_all(~cell_spec(.x, bold  = (.x == min))) %>%
  select(-min) %>% 
  rename(Constant = Const) %>% 
  kable(digits = 2, escape = F)
```

# moderators plot 

```{r}

best_fit_bmeasure_model_df <- readRDS(here("cached_data/best_fit_behavioral_measure_df.Rds"))
best_fit_exposure_phase_df <- readRDS(here("cached_data/best_fit_exposure_phase.Rds"))
best_fit_real_visual_df <- readRDS(here("cached_data/best_fit_real_visual_df.Rds"))
best_fit_real_aud_df <- readRDS(here("cached_data/best_fit_real_aud_df.Rds"))
best_fit_major_author_df <- readRDS(here("cached_data/best_fit_major_author_df.Rds"))

```


```{r}
# baseline is looking 
bmeasure_df <- best_fit_bmeasure_model_df %>% 
  filter(grepl("behavioral_measure", term)) %>% 
  mutate(term_print = case_when(
    grepl("other", term) ~ "Behavioral Measure - Other", 
    TRUE ~ "Behavioral Measure - Sucking"
  )) %>% 
  select(dataset, term_print, estimate, std.error) 

# baseline is conditionining 

ep_df <- best_fit_exposure_phase_df %>% 
  filter(grepl("exposure_phase", term)) %>% 
  mutate(term_print = case_when(
    grepl("habituation", term) ~ "Exposure phase - Habituation", 
    grepl("test_only", term) ~ "Exposure phase - Familiarization", 
    grepl("familiarization", term) ~ "Exposure phase - Test only"
  )) %>% 
  select(dataset, term_print, estimate, std.error) 

rv_df <- best_fit_real_visual_df %>% 
  filter(grepl("visual", term)) %>% 
  mutate(term_print = "Visual stimulus type - Representation") %>% 
  select(dataset, term_print, estimate, std.error) 


av_df <- best_fit_real_aud_df %>% 
  filter(grepl("aud", term)) %>% 
  mutate(term_print = "Auditory stimulus type - Natural") %>% 
  select(dataset, term_print, estimate, std.error) 

ma_df <- best_fit_major_author_df %>% 
  filter(grepl("author", term)) %>% 
  mutate(term_print = "By Major Author") %>% 
  select(dataset, major_author, term_print, estimate, std.error)
```


```{r}
all_mod_df <- bind_rows(bmeasure_df, ep_df, rv_df, av_df, ma_df) %>% 
  mutate(lb = estimate - std.error  * 1.96, 
         ub = estimate + std.error * 1.96) %>% 
  separate(term_print, into = c("type", "group"), sep = "-")
```


## bmeasure


## behavioral measure

```{r}

bm_p <- 
all_mod_df %>% 
  filter(grepl("Behavioral", type)) %>% 
  ggplot(aes(x = reorder(dataset,estimate), y = estimate, color = group)) + 
  geom_pointrange(aes(y = estimate, ymin = lb, ymax = ub), 
                   position = position_dodge(width = .4)) +
  geom_hline(yintercept = 0, linetype = "dashed")+ 
  coord_flip() +
  xlab("") + 
  ylab("") + 
  labs(title = "Behavioral Measure (Baseline: looking)") + 
  theme_few() +
  theme(
    legend.position = c(0.8, 0.15),
    legend.title = element_blank(),
    legend.background = element_rect(fill = NA, color = NA), 
    legend.text=element_text(size=6),
    plot.title = element_text(hjust = 0.5, size = 10)
  )  
```

## exposure phase

```{r}

ep_mod_p <- 
all_mod_df %>% 
  filter(grepl("Exposure", type)) %>% 
  ggplot(aes(x = reorder(dataset,estimate), y = estimate, color = group)) + 
  geom_pointrange(aes(y = estimate, ymin = lb, ymax = ub), 
                   position = position_dodge(width = .4)) +
  geom_hline(yintercept = 0, linetype = "dashed")+ 
  coord_flip() +
    scale_x_discrete(position = "top")+
  xlab("") + 
  ylab("") + 
  labs(title = "Exposure phase (Baseline: Conditioning)") + 
  theme_few() +
  theme(
    legend.position = c(0.8, 0.15),
    legend.title = element_blank(),
    legend.background = element_rect(fill = NA, color = NA), 
    legend.text=element_text(size=6),
    plot.title = element_text(hjust = 0.5, size = 10)
  )  
```

## visual 

```{r}

vr_mod_p <- 
all_mod_df %>% 
  filter(grepl("Visual stimulus", type)) %>% 
  ggplot(aes(x = reorder(dataset,estimate), y = estimate, color = group)) + 
  geom_pointrange(aes(y = estimate, ymin = lb, ymax = ub), 
                   position = position_dodge(width = .4)) +
  geom_hline(yintercept = 0, linetype = "dashed")+ 
  coord_flip() +
  scale_x_discrete(position = "top")+
  xlab("") + 
  ylab("") + 
  labs(title = "Visual stimulus type (Baseline: real stimulus)") + 
  theme_few() +
  theme(
    legend.position = c(0.8, 0.1),
    legend.title = element_blank(),
    legend.background = element_rect(fill = NA, color = NA), 
    legend.text=element_text(size=6),
    plot.title = element_text(hjust = 0.5, size = 10)
  )  
```

## auditory 

```{r}
ar_mod_p <- all_mod_df %>% 
  filter(grepl("Auditory stimulus", type)) %>% 
  ggplot(aes(x = reorder(dataset,estimate), y = estimate, color = group)) + 
  geom_pointrange(aes(y = estimate, ymin = lb, ymax = ub), 
                   position = position_dodge(width = .4)) +
  geom_hline(yintercept = 0, linetype = "dashed")+ 
  coord_flip() +
  xlab("") + 
  ylab("") + 
  labs(title = "Auditory stimulus type (Baseline: artificial stimulus)") + 
  theme_few() +
  theme(
    legend.position = c(0.8, 0.1),
    legend.title = element_blank(),
    legend.background = element_rect(fill = NA, color = NA), 
    legend.text=element_text(size=6),
    plot.title = element_text(hjust = 0.5, size = 10)
  )  
```

## Major author? 

```{r}
ma_p <-
all_mod_df %>% 
  filter(grepl("Author", type)) %>% 
  ggplot(aes(x = dataset, y = estimate, group = major_author)) + 
  geom_pointrange(aes(y = estimate, ymin = lb, ymax = ub), 
                   position = position_dodge(width = .4)) +
  geom_hline(yintercept = 0, linetype = "dashed")+ 
  xlab("") + 
  ylab("") + 
  labs(title = "Major author (Baseline: Non-Major author)") + 
  theme_few() +
  theme(
    legend.position = c(0.8, 0.1),
    legend.title = element_blank(),
    legend.background = element_rect(fill = NA, color = NA), 
    legend.text=element_text(size=6),
    plot.title = element_text(hjust = 0.5, size = 10),
    axis.text.x = element_text(angle = 45, hjust=1)
  )  

ma_p
```
## putting things together

```{r fig.width=15, fig.height=10}
library(patchwork)

(bm_p | ep_mod_p) / (ar_mod_p  | vr_mod_p)
```


# devo curves

```{r}
saveRDS(all_age_pred, here("cached_data/min_age_pred_df.RDS"))

all_age_pred <- readRDS(here("cached_data/min_age_pred_df.RDS"))

age_range_df <- d %>% 
  group_by(ds_clean) %>% 
  summarise(min_age = min(mean_age_months, na.rm = TRUE), 
            max_age = max(mean_age_months, na.rm = TRUE)) %>% 
  rename(ds_name = ds_clean)


sig_ds <- c("Mutual exclusivity", "Audio-Visual Congruence", "Mispronunciation sensitivity",
           "Statistical sound category learning (habituation)", "Simple arithmetic competences")

categorized_age_pred_df <- all_age_pred %>% 
  select(pred, ds_name, ci.ub, ci.lb) %>% 
  group_by(ds_name) %>% 
  mutate(mean_age_months = (row_number() + 1) / 2) %>% 
  left_join(age_range_df, by = c("ds_name")) %>% 
  filter(mean_age_months > min_age, 
         mean_age_months < min(36, max_age)) %>% 
  mutate(
    ds_type = case_when(
      ds_name %in% c( "Language discrimination and preference", 
                     "Mispronunciation sensitivity", 
                     "Natural speech preference", "Sound symbolism", "Statistical sound category learning (habituation)", 
                     "Vowel discrimination (native)",
                     "Vowel discrimination (non-native)" ,"Word Segmentation (combined)",
                     "Statistical word segmentation", "Audio-Visual Congruence") ~ "Sounds", 
      
      ds_name %in% c("Familiar word recognition", 
                     "Cross-situational word learning", 
                      "Label advantage in concept learning",
                     "Mutual exclusivity",
                     "Online word recognition",
                     "Syntactic bootstrapping",
                     "Switch task") ~ "Words",
      
      ds_name %in% c("Gaze following (combined)",
                     "Neonatal Imitation",
                     "Prosocial agents",
                     #"Symbolic play", 
                     "Infant directed speech preference") ~ "Communication", 
      
      ds_name %in% c("Abstract rule learning",  
                     "Categorization bias", 
                     "Simple arithmetic competences") ~ "Cognitive"
     )
  ) %>% 
  mutate(pred = case_when(
    ds_name == "Abstract rule learning" ~ -pred, 
    ds_name == "Switch task" ~ -pred,
    TRUE ~ pred
  )) %>% 
  select(ds_name, ds_type, mean_age_months, pred, ci.ub, ci.lb) %>% 
  mutate(
    ds_name = case_when(
      ds_name %in% sig_ds ~ paste0(ds_name, "*"), 
      TRUE ~ ds_name
    ), 
    sig_alpha = case_when(
      ds_name %in% sig_ds  ~ 1, 
      TRUE ~ .3
    )
  )



label_df <- categorized_age_pred_df %>% 
  filter(mean_age_months == max(mean_age_months)) 

label_df$x = c(
    13 + 4,#Abstract rule learning
    0 + 8, # audio visual
    35.5 + 5 , # Categorization bias
    35.5 + 3, # "Cross-situational word learning"
    15 + 3,#Familiar word recognition
    23.5 + 4, #"Gaze following (combined)",,
    15 - 3, # Label advantage
    11.5 + 8, # "Language discrimination and preference"
    35.5 + 4,#"Mispronunciation sensitivity"
    35.5 + 4, #Mutual exclusivity , 
    12.5 , #"Natural speech preference"
    0 + 4, #neonatal imitation 
    30 + 2, #"Online word recognition"
    31.5 + 8, #Prosocial Agents
    9 + 4, #"Simple arithmetic competences"
    35.5 + 8, #Sound symbolism, 
    11 + 5, #"Statistical sound category learning (habituation)"
    18.5, #"Statistical word segmentation"
    24.5+ 3, #Switch task,
    35.5 + 5, # "Syntactic bootstrapping"
    17.5 - 5, #"Vowel discrimination (non-native)"
    29.5 + 11, #"Vowel discrimination (native)"
    24.5 + 14, #"Word Segmentation (combined)"
    18.5# "Infant directed speech preference"
)
label_df$y = c(
  0.05 - 0.5,#Abstract rule learning
  0 + 1.5, # audio visual
  0.275 + .4, # Categorization bias
  0.545 + .3, # "Cross-situational word learning"
  0.805 + 0.3,#Familiar word recognition
  2.99 + 0.3, #"Gaze following (combined)"
  0.05004268 - 0.5, # label advantage
  0.265 - 1, # "Language discrimination and preference"
  1.62 + 0.5,#"Mispronunciation sensitivity"
  1.44 + 0.3,#Mutual exclusivity
  0.811 + 1.3, #"Natural speech preference"
  0 + 1.5, # neonatal imitation 
  2.964331 + 0.5, #"Online word recognition"
  0.405, #Prosocial agents
  0.249 + 0.6,#"Simple arithmetic competences"
  0.383, #Sound symbolism, 
  0.557 + 0.5, #"Statistical sound category learning (habituation)"
  -0.07808538 - 0.2, #"Statistical word segmentation"
  0.156 - 0.3,#Switch task
  0.103 - 0.5, # "Syntactic bootstrapping"
  0.5901183 + 0.2, #"Vowel discrimination (native)"
  0.6457766 + 1, #"Vowel discrimination (non-native)"
  0.2 + 1.2, #"Word Segmentation (combined)"
 0.467 - 0.6# "Infant directed speech preference", 
 #0.627 + 0.5, #Symbolic play
)

p <- categorized_age_pred_df %>% 
  ggplot(aes(x = mean_age_months, y = pred, group = ds_name, color = ds_name)) + 
  geom_hline(yintercept = 0, linetype = "dashed", alpha = .5) + 
  geom_line(aes(alpha = sig_alpha), width = 2)+ 
  geom_ribbon(
              aes(x = mean_age_months, y = pred, ymin = ci.lb, ymax = ci.ub, fill = ds_name), alpha = 0.1, colour = NA)+ 
  geom_text(data = label_df, aes(x = x, y = y, label = ds_name), 
                   size = 2.2,
                  segment.color = NA) + 
  xlim(0, 48) + 
  ylim(-2, 4) + 
  facet_wrap(~ds_type, scales = "free") + 
  theme_few()+
  theme(legend.position = "none") + 
  xlab("Age (months)") + 
  ylab("Predicted Value")
  

p
```
label_df$ds_name
label_df$mean_age_months
label_df$pred




