```{r}
library(tidyverse)
library(here)

d <- read_csv(here("data/metalab_data_mini.csv")) 
all_age_pred<-readRDS(here("cached_data/full_age_pred_df.RDS"))
```


```{r}
age_range_df <- d %>% 
  group_by(ds_clean) %>% 
  summarise(min_age = min(mean_age_months, na.rm = TRUE), 
            max_age = max(mean_age_months, na.rm = TRUE)) %>% 
  rename(ds_name = ds_clean)

age_pred_d <- all_age_pred %>% 
  mutate(
    model_type = case_when(
      !is.na(X.mean_age_months) ~ "linear", 
      !is.na(X.log.mean_age_months.) ~ "log", 
      !is.na(X.I.mean_age_months.2.) ~ "quad", 
      TRUE ~ "constant"
    )
  ) %>% 
  select(pred, ds_name, ci.ub, ci.lb, model_type) %>% 
  group_by(ds_name, model_type) %>% 
  mutate(mean_age_months = (row_number() / 2) - 0.5) %>% 
  left_join(age_range_df, by = c("ds_name")) %>% 
  rowwise() %>% 
  filter(if(ds_name != "Neonatal Imitation") mean_age_months >= min_age & mean_age_months < min(36, max_age) else mean_age_months >=0 & mean_age_months < min(36, max_age)) %>% 
  mutate(pred = case_when(
    ds_name == "Abstract rule learning" ~ -pred, 
    ds_name == "Switch task" ~ -pred,
    TRUE ~ pred
  ), 
  ci.ub = 
    case_when(
    ds_name == "Abstract rule learning" ~ -ci.lb, 
    ds_name == "Switch task" ~ -ci.lb,
    TRUE ~ ci.ub
  ),
   ci.lb = 
    case_when(
    ds_name == "Abstract rule learning" ~ -ci.ub, 
    ds_name == "Switch task" ~ -ci.ub,
    TRUE ~ ci.lb
  )
  
  ) %>% 
  select(ds_name, mean_age_months, pred, ci.ub, ci.lb, model_type) %>% 
  ungroup()

clean_d <- d %>% 
  mutate( 
    d_calc = case_when(
      ds_clean == "Abstract rule learning" ~ -d_calc, 
    ds_clean == "Switch task" ~ -d_calc,
    TRUE ~ d_calc)) %>% 
  mutate(ds_clean = case_when(
      ds_clean == "Cross-situational word learning" ~ "X-situation learning", 
      ds_clean == "Label advantage in concept learning" ~ "Label advantage",
      ds_clean == "Language discrimination and preference (discrimination)" ~ "Language discrimination",       
      ds_clean == "Audio-Visual Congruence" ~ "Audio-visual congruen.", 
      ds_clean == "Language discrimination and preference (preference)" ~ "Language preference",
      ds_clean == "Cross-situational word learning"  ~ "X-situation learning",
      ds_clean == "Gaze following (combined)" ~ "Gaze following", 
      ds_clean == "Label advantage in concept learning" ~ "Label advantage", 
      ds_clean == "Statistical sound category learning" ~ "Stat. category learning",
      ds_clean == "Statistical word segmentation" ~ "Stat. word seg.",
      ds_clean == "Word Segmentation (combined)" ~ "Word segmentation", 
      ds_clean == "Infant directed speech preference" ~ "IDS pref.",
      TRUE ~ ds_clean
  )) %>% 
  rename(ds_name = ds_clean) %>% 
  filter(mean_age_months <= 36)




```


```{r fig.width=9, fig.height=10}
age_pred_d %>% 
  # this is to handle the tricky part with neonatal imitation
  filter(pred != -Inf) %>% 
  mutate(group_var = paste0(ds_name, model_type)) %>% 
  mutate(
     ds_name = case_when(
       ds_name == "Cross-situational word learning" ~ "X-situation learning", 
      ds_name == "Audio-Visual Congruence" ~ "Audio-visual congruen.", 
      ds_name == "Label advantage in concept learning" ~ "Label advantage",
      ds_name == "Language discrimination and preference (discrimination)" ~ "Language discrimination", 
      ds_name == "Language discrimination and preference (preference)" ~ "Language preference",
      ds_name == "Cross-situational word learning"  ~ "X-situation learning",
      ds_name == "Gaze following (combined)" ~ "Gaze following", 
      ds_name == "Label advantage in concept learning" ~ "Label advantage", 
      ds_name == "Statistical sound category learning" ~ "Stat. category learning",
      ds_name == "Statistical word segmentation" ~ "Stat. word seg.",
      ds_name == "Word Segmentation (combined)" ~ "Word segmentation", 
      ds_name == "Infant directed speech preference" ~ "IDS pref.",
      TRUE ~ ds_name
  )) %>% 
  mutate(
    model_type = case_when(
      model_type == "constant" ~ "Constant", 
      model_type == "linear" ~ "Linear", 
      model_type == "quad" ~ "Quadratic", 
      model_type == "log" ~ "Logarithmic"
    )
  ) %>% 

  ggplot(aes(x = mean_age_months,  y = pred)) + 
  geom_hline(yintercept = 0, linetype ="dotted", alpha = .5) + 
  geom_point(data = clean_d , 
            aes(x = mean_age_months, y = d_calc),size = .5, alpha = .5) + 
  geom_line(alpha = 1,  aes(group = group_var,color = model_type)) + 
  
 geom_ribbon(
              aes(x = mean_age_months, group = group_var,y = pred, ymin = ci.lb, ymax = ci.ub, fill = model_type), alpha = 0.2, colour = NA)+ 

    theme_few()+
     guides(color=guide_legend(title="Model Type")) + 
guides(fill = "none") + 
xlab("Mean age (months)") + 
  ylab("Predicted ES") + 
  
   theme(legend.position = "top", 
         strip.text = element_text(size = 11, margin = margin())) + 
  
  facet_wrap(~ds_name, scales = "free_x",
             labeller = label_wrap_gen()) -> fig_1

saveRDS(fig_1, here("writing/display_items/figure_1.Rds"))
```

```{r fig.width=9, fig.height=10}
age_pred_d %>% 
  # this is to handle the tricky part with neonatal imitation
  filter(pred != -Inf) %>% 
  mutate(group_var = paste0(ds_name, model_type)) %>% 
  mutate(
     ds_name = case_when(
       ds_name == "Cross-situational word learning" ~ "X-situation learning", 
      ds_name == "Audio-Visual Congruence" ~ "Audio-visual congruen.", 
      ds_name == "Label advantage in concept learning" ~ "Label advantage",
      ds_name == "Language discrimination and preference (discrimination)" ~ "Language discrimination", 
      ds_name == "Language discrimination and preference (preference)" ~ "Language preference",
      ds_name == "Cross-situational word learning"  ~ "X-situation learning",
      ds_name == "Gaze following (combined)" ~ "Gaze following", 
      ds_name == "Label advantage in concept learning" ~ "Label advantage", 
      ds_name == "Statistical sound category learning" ~ "Stat. category learning",
      ds_name == "Statistical word segmentation" ~ "Stat. word seg.",
      ds_name == "Word Segmentation (combined)" ~ "Word segmentation", 
      ds_name == "Infant directed speech preference" ~ "IDS pref.",
      TRUE ~ ds_name
  )) %>% 
  mutate(
    model_type = case_when(
      model_type == "constant" ~ "Constant", 
      model_type == "linear" ~ "Linear", 
      model_type == "quad" ~ "Quadratic", 
      model_type == "log" ~ "Logarithmic"
    )
  ) %>% 

  ggplot(aes(x = mean_age_months,  y = pred)) + 
  geom_hline(yintercept = 0, linetype ="dotted", alpha = .5) + 
  geom_point(data = clean_d , 
            aes(x = mean_age_months, y = d_calc),size = .5, alpha = .5) + 
  geom_line(alpha = 1,  aes(group = group_var,color = model_type)) + 
  
 geom_ribbon(
              aes(x = mean_age_months, group = group_var,y = pred, ymin = ci.lb, ymax = ci.ub, fill = model_type), alpha = 0.2, colour = NA)+ 

    theme_few()+
     guides(color=guide_legend(title="Model Type")) + 
guides(fill = "none") + 
xlab("Mean age (months)") + 
  ylab("Predicted ES") + 
  
   theme(legend.position = "top", 
         strip.text = element_text(size = 8, margin = margin())) + 
  
  scale_y_log10()+
  
  
  facet_wrap(~ds_name, scales = "free",
             labeller = label_wrap_gen()) -> fig_1_freey_log

saveRDS(fig_1_freey_log, here("writing/display_items/fig_1_freey_log.Rds"))


```

