---
output:
  pdf_document: default
  html_document: default
---

# Table 1

includes: 
- name, - done
- number of effect sizes - done
- number of participants - done
- Age Range - done
- Meta-analytic effect sizes + confidence interval - done
- I^2 - done
- Associated paper

```{r}
library(tidyverse)
library(metafor)
library(here)
source(here("analysis/helper/summary_table_help.r"))

d <- read_csv(here("data/metalab_data_kitchensink.csv")) 

```

## get effect sizes 

```{r}
nested_d <- d %>% 
  group_by(ds_clean) %>% 
  nest() 
  

es_df <- lapply(
  nested_d$ds_clean, 
  function(name){
    data = (nested_d %>% filter(ds_clean == name))$data[[1]]
    es <- get_ma_effect_size(data) %>% mutate(ds_clean = name)
  }
) %>% bind_rows() %>% 
  mutate_if(is.numeric, round, 2) %>% 
  mutate(
    es_print = paste0(es, " [", es_lb, ", ", es_ub, "]")
  )
```


```{r}
sample_size_d <- d %>% 
  mutate(n_2 = ifelse(is.na(n_2), 0, n_2)) %>% 
  distinct(ds_clean, same_infant, n_1, n_2) %>% 
  mutate(total_infants = n_1 + n_2) %>% 
  group_by(ds_clean) %>% 
  summarise(n = sum(total_infants)) %>% 
  rename(n_sample_size = n)

d_data <- d %>% 
  group_by(ds_clean) %>% 
  summarise(
    n_effect_size = n(), 
    min_age = round(min(mean_age_months), 2), 
    max_age = round(max(mean_age_months), 2)
  ) %>% 
  mutate(
    age_range_print = paste0("[", min_age, " ,", max_age, "]")
  ) %>% 
  select(-min_age, -max_age) %>% 
  left_join(sample_size_d, by = c("ds_clean")) %>% 
  left_join(es_df %>% select(es_print, i2, ds_clean), by = c("ds_clean")) %>% 
  select(ds_clean, n_effect_size, n_sample_size, es_print, i2)

full_d <- d_data %>% 
  mutate(paper = case_when(
    ds_clean == "Abstract rule learning" ~ "Rabagliati, Ferguson, & Lew-Williams (2018)", 
    ds_clean == "Audio-Visual Congruence" ~ "Cox, Keren-Portnoy, Roepstorff, & Fusaroli (2022)",
    ds_clean == "Categorization bias" ~ "NA", 
    ds_clean == "Cross-situational word learning" ~ "NA", 
    ds_clean == "Familiar word recognition" ~ "Carbajal, Peperkamp, & Tsuji (2021)", 
    ds_clean == "Gaze following (combined)" ~ "Frank, Lewis, & MacDonald (2016)", 
    ds_clean == "Label advantage in concept learning" ~ "NA",
    ds_clean == "Language discrimination and preference (discrimination)" ~ "Gasparini, Langus, Tsuji, & Boll-Avetisyan (2021)", 
    ds_clean == "Language discrimination and preference (preference)" ~ "Gasparini, Langus, Tsuji, & Boll-Avetisyan (2021)", 
    ds_clean == "Mispronunciation sensitivity" ~ "Von Holzen & Bergmann (2021)", 
    ds_clean == "Mutual exclusivity" ~ "Lewis et al. (2020)", 
    ds_clean == "Natural speech preference" ~ "Issard, Tsuji, & Cristia (2023)", 
    ds_clean == "Neonatal Imitation" ~ "Davis et al. (2021)", 
    ds_clean == "Online word recognition" ~ "Frank, Lewis, & MacDonald (2016)", 
    ds_clean == "Prosocial agents" ~ "Margoni & Surian (2018)", 
    ds_clean == "Simple arithmetic competences" ~ "Christodoulou, Lac, & Moore (2017)", 
    ds_clean == "Sound symbolism" ~ "Fort et al. (2018)", 
    ds_clean == "Statistical sound category learning" ~ "Cristia (2018)", 
    ds_clean == "Statistical word segmentation" ~ "Black & Bergmann (2017)", 
    ds_clean == "Switch task" ~ "Tsui, Byers-Heinlein, & Fennell (2019)", 
    ds_clean == "Syntactic bootstrapping" ~ "Cao & Lewis (2022)", 
    ds_clean == "Vowel discrimination (native)" ~ "Tsuji & Cristia (2014)", 
    ds_clean == "Vowel discrimination (non-native)" ~ "Tsuji & Cristia (2014)", 
    ds_clean == "Word Segmentation (combined)" ~ "Bergmann & Cristia (2016)", 
    ds_clean == "Infant directed speech preference" ~ "Dunst, Gorman, & Hamby (2012); Zettersten et al., (2023)"
  )) %>% 
  mutate(
    ds_clean = case_when(
      ds_clean == "Audio-Visual Congruence" ~ "Audio-visual congruence" , 
      ds_clean == "Language discrimination and preference (discrimination)" ~ "Language discrimination", 
      ds_clean == "Language discrimination and preference (preference)" ~ "Language preference",
      ds_clean == "Word Segmentation (combined)" ~ "Word segmentation (combined)", 
      TRUE ~ ds_clean
    )
  ) %>% 
  mutate(n_sample_size = as.integer(n_sample_size)) %>% 
  rename(
    Dataset = ds_clean, 
    'N ES' = n_effect_size, 
    'N Subject' = n_sample_size, 
    'MA ES' = es_print, 
    'Citation' = paper
  ) 
```

```{r}
saveRDS(full_d, here("writing/display_items/table_1.Rds"))
```

