

```{r}
library(tidyverse)


```

# age-related selection bias 

```{r}
fake_data <- tibble(
  x = seq(1, 36, 1), 
 
) %>% 
  mutate( y = .5 + 0*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -10, max = 10) ) %>% 
  mutate(type = "Published Data") %>% 
   bind_rows(
    tibble(
  x = seq(1, 18, .5), 
 ) %>% 
    mutate( y = .5 + .6*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -20, max = -5) ) %>% 
   mutate(type = "Unpublished Data")
 
 ) %>% 
  mutate(full_cat = "full")
  
  
p1 <- fake_data %>%     
  ggplot(aes(x = x, y = y)) + 
  geom_point(position = position_jitter(width = .2), aes( color = type)) + 
  #scale_shape_manual(values=c(19, 3))+
  scale_color_manual(values = c("black", "gray")) +
  #geom_hline(yintercept = -5, color = "black") + 
  
  geom_smooth(
    data = fake_data %>% filter(type != "Unpublished Data"), aes(x = x, y = y), method = "lm", se = TRUE,
    color = "gray") + 
 geom_smooth(
    data = fake_data, aes(x = x, y = y), method = "lm", se = FALSE, 
    color = "red", linetype = "dashed") + 
  theme_few()+ 
  xlab("Age")+ 
  ylab("Effect Size") + 
  guides(color=guide_legend(title="")) + 
  theme(
    legend.position = "bottom",
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
    axis.text.y=element_blank(),
      axis.ticks.y=element_blank()
  )# + 
  #ggtitle("Age-related Publication Bias") +
  #theme(plot.title = element_text(hjust = 0.5, size = 8))

p1
```

# age related method selection 

```{r}
fake_data <- tibble(
  x = seq(1, 18, 1), 
 
) %>% 
  mutate( y = 14 + 1*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -10, max = 10) ) %>% 
  mutate(type = "Method A") %>% 
   bind_rows(
    tibble(
  x = seq(18, 36, .5), 
 ) %>% 
    mutate( y = -1 + .6*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -10, max = 10) ) %>% 
   mutate(type = "Method B")
 
 ) %>% 
  mutate(full_cat = "full")

p2 <-fake_data %>%     
  ggplot(aes(x = x, y = y)) + 
  geom_point(position = position_jitter(width = .2), aes( color = type)) + 
  scale_color_manual(values=c("black", "darkgray"))+
  geom_smooth(
    data = fake_data %>% filter(type == "Method A"), aes(x = x, y = y), method = "lm", se = FALSE,
    color = "red", linetype = "dashed") + 
  geom_smooth(
    data = fake_data %>% filter(type == "Method B"), aes(x = x, y = y), method = "lm", se = FALSE,
    color = "red", linetype = "dashed") +
 geom_smooth(
    data = fake_data, aes(x = x, y = y), method = "lm", se = TRUE, 
    color = "gray") + 
  theme_few()+ 
  xlab("Age")+ 
  ylab("Effect Size") + 
  guides(color=guide_legend(title="")) + 
  theme(
    legend.position = "bottom",
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
    axis.text.y=element_blank(),
      axis.ticks.y=element_blank()
  ) #+ 
  #ggtitle("Age-related Methods Adaptation") +
  #theme(plot.title = element_text(hjust = 0.5, size = 8))

p2
```

`
# theoretical constraints 

```{r}
fake_data <- tibble(
  x = seq(1, 36, 1), 
 
) %>% 
  mutate( y = 0.5 + .9*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -10, max = 10) ) %>% 
  mutate(type = "Subsample A") %>% 
   bind_rows(
    tibble(
  x = seq(1, 36, 1), 
 ) %>% 
    mutate( y = .5 -.4*x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -15, max = 8) ) %>% 
   mutate(type = "Subsample B")
 
 ) %>% 
  mutate(full_cat = "full")

p3 <-fake_data %>%     
  ggplot(aes(x = x, y = y)) + 
  geom_point(position = position_jitter(width = .2), aes( color = type)) + 
  scale_color_manual(values=c("black", "darkgray"))+
  geom_smooth(
    data = fake_data %>% filter(type ==  "Subsample A"), aes(x = x, y = y), method = "lm", se = FALSE,
    color = "red", linetype = "dashed") + 
 # geom_smooth(
#    data = fake_data %>% filter(type == "Subsample B"), aes(x = x, y = y), method = "lm", se = FALSE,
#    color = "red", linetype = "dashed") +
 geom_smooth(
    data = fake_data, aes(x = x, y = y), method = "lm", se = TRUE, 
    color = "gray") + 
  theme_few()+ 
  xlab("Age")+ 
  ylab("Effect Size") + 
  guides(color=guide_legend(title="")) + 
  theme(
    legend.position = "bottom",
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
    axis.text.y=element_blank(),
      axis.ticks.y=element_blank()
  ) #+ 
  #ggtitle("Theoretical factors") +
  #theme(plot.title = element_text(hjust = 0.5, size = 8))

p3
```



```{r}
fake_data <- tibble(
  x = seq(1, 12, .3), 
 
) %>% 
  mutate( y = -5 ) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -10, max = 20) ) %>% 
  mutate(type = "Infants") %>% 
   bind_rows(
    tibble(
  x = seq(15, 36, 1), 
 ) %>% 
    mutate( y = -30+ 1 *x) %>%
  rowwise() %>% 
  mutate(y = y +  runif(1, min = -5, max = 10 )) %>% 
   mutate(type = "Toddlers")
 
 ) %>% 
  mutate(full_cat = "full")

p4 <- fake_data %>%     
  ggplot(aes(x = x, y = y)) + 
  geom_point(position = position_jitter(width = .2), aes( color = type)) + 
  scale_color_manual(values=c("black", "darkgray"))+
 # geom_smooth(
#    data = fake_data %>% filter(type ==  "Infants"), aes(x = x, y = y), method = "lm", se = FALSE,
#    color = "gray", linetype = "dashed") + 
  geom_smooth(
    data = fake_data %>% filter(type == "Toddlers"), aes(x = x, y = y), method = "lm", se = FALSE,
    color = "red", linetype = "dashed") +
 geom_smooth(
    data = fake_data, aes(x = x, y = y), method = "lm", se = TRUE, 
    color = "gray") + 
  theme_few()+ 
  xlab("Age")+ 
  ylab("Effect Size") + 
  guides(color=guide_legend(title="")) + 
  theme(
    legend.position = "bottom",
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
    axis.text.y=element_blank(),
      axis.ticks.y=element_blank())
  #ggtitle("Developmnetal Discontinuity") +
  #theme(plot.title = element_text(hjust = 0.5, size = 8))

p4
```



```{r}
library(cowplot)
library(patchwork)

gg_axis <- cowplot::get_plot_component(ggplot() +
  labs(x = "Hp // Cyl"), "xlab-b")

plot_grid(p1, p2, p3, p4,labels = c("A", "B", "C", "D"))

(p1 + p2 + p3 + p4 ) / gg_axis + plot_layout(heights = c(40, 1))
```

